name: workflow for Codecov
on: [push]
jobs:
    run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - name: Setup Node.js
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: 16
            - name: Install Packages
              run: |
                  npm install pnpm -g
                  npm install
            - name: Generate coverage report
              run: npm run coverage
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  directory: ./coverage/
                  fail_ci_if_error: true
                  flags: unittests
                  name: promptor-coverage
